.TH FILE_MANAGER 1 "May 2024" "File Manager Manual"
.SH NAME
file_manager \- program for managing files and directories

.SH SYNOPSIS
.B file_manager

.SH DESCRIPTION
file_manager is a command-line program that provides various operations for managing files and directories.

.SH OPTIONS
The following options are available:
.TP
.B 1
List files and directories in the current directory.
.TP
.B 2
Change permissions of a file.
.TP
.B 3
Make or delete files/directories.
.TP
.B 4
Create symbolic link files.
.TP
.B 5
Exit the program.

.SH AUTHOR
Written by Doaa.
